/* Teradata DDL */

CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.BINS (
  TABLENAME TITLE 'TABLENAME' VARCHAR(128) NOT NULL
  , COLUMNNAME TITLE 'COLUMNNAME' VARCHAR(128) NOT NULL
  , BINVALUE TITLE 'BINVALUE' VARCHAR(128) NOT NULL
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.CLASSIFICATIONS (
  TABLENAME TITLE 'TABLENAME' VARCHAR(128) NOT NULL
  , VALUECODE TITLE 'VALUECODE' VARCHAR(128) NOT NULL
  , DISPLAYNAME TITLE 'DISPLAYNAME' VARCHAR(128) NOT NULL
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.CLEANSING_RULES (
  TABLENAME TITLE 'TABLENAME' VARCHAR(128) NOT NULL
  , COLUMNNAME TITLE 'COLUMNNAME' VARCHAR(128) NOT NULL
  , RULETYPE TITLE 'RULETYPE' VARCHAR(128) NOT NULL
  , RULEPARAM TITLE 'RULEPARAM' VARCHAR(128) NOT NULL
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.COLUMN_LABEL (
  TABLENAME TITLE 'TABLENAME' VARCHAR(128) NOT NULL
  , COLUMNNAME TITLE 'COLUMNNAME' VARCHAR(128) NOT NULL
  , LABEL TITLE 'LABEL' VARCHAR(128) NOT NULL
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.Company (
  code TITLE 'code' VARCHAR(10) NOT NULL
  , name TITLE 'name' VARCHAR(10) NOT NULL
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.COUNT_DEFAULT (
  TABLENAME TITLE 'TABLENAME' VARCHAR(128) NOT NULL
  , COLUMNNAME TITLE 'COLUMNNAME' VARCHAR(128) NOT NULL
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.CUBE (
  TABLENAME TITLE 'TABLENAME' VARCHAR(128) NOT NULL
  , VALUESETNAME TITLE 'VALUESETNAME' VARCHAR(128) NOT NULL
  , COLUMNNAME TITLE 'COLUMNNAME' VARCHAR(128) NOT NULL
  , CODE TITLE 'CODE' VARCHAR(128) NOT NULL
  , FLAGS TITLE 'FLAGS' VARCHAR(16) NOT NULL
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.C_Age (
  Code TITLE 'Code' INTEGER NOT NULL
  , Name TITLE 'Name' VARCHAR(128) NOT NULL
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.C_Age_Five_Group_1 (
  Code TITLE 'Code' INTEGER NOT NULL
  , Name TITLE 'Name' VARCHAR(20) NOT NULL
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.C_Age_Group_0 (
  Code TITLE 'Code' INTEGER NOT NULL
  , Name TITLE 'Name' VARCHAR(20) NOT NULL
  , FK_5Group TITLE 'FK_5Group' INTEGER NOT NULL
  , FK_10Group TITLE 'FK_10Group' INTEGER NOT NULL
  , FOREIGN KEY (FK_10Group)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.C_Age_Ten_Group_1 (Code)
  , FOREIGN KEY (FK_5Group)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.C_Age_Five_Group_1 (Code)
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.C_Age_Ten_Group_1 (
  Code TITLE 'Code' INTEGER NOT NULL
  , Name TITLE 'Name' VARCHAR(20) NOT NULL
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.C_Cal_Date_0 (
  Code TITLE 'Code' INTEGER NOT NULL
  , Name TITLE 'Name' VARCHAR(32) NOT NULL
  , FK_Month TITLE 'FK_Month' INTEGER NOT NULL
  , FOREIGN KEY (FK_Month)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.C_Cal_Date_1 (Code)
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.C_Cal_Date_1 (
  Code TITLE 'Code' INTEGER NOT NULL
  , Name TITLE 'Name' VARCHAR(32) NOT NULL
  , FK_Quarter TITLE 'FK_Quarter' INTEGER NOT NULL
  , FOREIGN KEY (FK_Quarter)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.C_Cal_Date_2 (Code)
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.C_Cal_Date_2 (
  Code TITLE 'Code' INTEGER NOT NULL
  , Name TITLE 'Name' VARCHAR(32) NOT NULL
  , FK_Year TITLE 'FK_Year' INTEGER NOT NULL
  , FOREIGN KEY (FK_Year)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.C_Cal_Year (Code)
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.C_Cal_Last_Tran_Date_0 (
  Code TITLE 'Code' INTEGER NOT NULL
  , Name TITLE 'Name' VARCHAR(32) NOT NULL
  , FK_Month TITLE 'FK_Month' INTEGER NOT NULL
  , FOREIGN KEY (FK_Month)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.C_Cal_Last_Tran_Date_1 (Code)
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.C_Cal_Last_Tran_Date_1 (
  Code TITLE 'Code' INTEGER NOT NULL
  , Name TITLE 'Name' VARCHAR(32) NOT NULL
  , FK_Quarter TITLE 'FK_Quarter' INTEGER NOT NULL
  , FOREIGN KEY (FK_Quarter)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.C_Cal_Last_Tran_Date_2 (Code)
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.C_Cal_Last_Tran_Date_2 (
  Code TITLE 'Code' INTEGER NOT NULL
  , Name TITLE 'Name' VARCHAR(32) NOT NULL
  , FK_Year TITLE 'FK_Year' INTEGER NOT NULL
  , FOREIGN KEY (FK_Year)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.C_Cal_Last_Tran_Year (Code)
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.C_Cal_Last_Tran_Year (
  Code TITLE 'Code' INTEGER NOT NULL
  , Name TITLE 'Name' VARCHAR(32) NOT NULL
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.C_Cal_Year (
  Code TITLE 'Code' INTEGER NOT NULL
  , Name TITLE 'Name' VARCHAR(32) NOT NULL
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.C_Cust_Mail_Indicator (
  Code TITLE 'Code' VARCHAR(50) NOT NULL
  , Name TITLE 'Name' VARCHAR(50) NOT NULL
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.C_DayOfMonth (
  Code TITLE 'Code' INTEGER NOT NULL
  , Name TITLE 'Name' VARCHAR(32) NOT NULL
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.C_Fin_Date_0 (
  Code TITLE 'Code' INTEGER NOT NULL
  , Name TITLE 'Name' VARCHAR(63) NOT NULL
  , FK_Month TITLE 'FK_Month' VARCHAR(10) NOT NULL
  , FOREIGN KEY (FK_Month)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.C_Fin_Date_1 (Code)
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.C_Fin_Date_1 (
  Code TITLE 'Code' VARCHAR(10) NOT NULL
  , Name TITLE 'Name' VARCHAR(45) NOT NULL
  , FK_Quarter TITLE 'FK_Quarter' VARCHAR(9) NOT NULL
  , FOREIGN KEY (FK_Quarter)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.C_Fin_Date_2 (Code)
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.C_Fin_Date_2 (
  Code TITLE 'Code' VARCHAR(9) NOT NULL
  , Name TITLE 'Name' VARCHAR(63) NOT NULL
  , FK_Year TITLE 'FK_Year' VARCHAR(8) NOT NULL
  , FOREIGN KEY (FK_Year)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.C_Fin_Year (Code)
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.C_Fin_Last_Tran_Date_0 (
  Code TITLE 'Code' INTEGER NOT NULL
  , Name TITLE 'Name' VARCHAR(63) NOT NULL
  , FK_Month TITLE 'FK_Month' VARCHAR(10) NOT NULL
  , FOREIGN KEY (FK_Month)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.C_Fin_Last_Tran_Date_1 (Code)
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.C_Fin_Last_Tran_Date_1 (
  Code TITLE 'Code' VARCHAR(10) NOT NULL
  , Name TITLE 'Name' VARCHAR(45) NOT NULL
  , FK_Quarter TITLE 'FK_Quarter' VARCHAR(9) NOT NULL
  , FOREIGN KEY (FK_Quarter)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.C_Fin_Last_Tran_Date_2 (Code)
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.C_Fin_Last_Tran_Date_2 (
  Code TITLE 'Code' VARCHAR(9) NOT NULL
  , Name TITLE 'Name' VARCHAR(63) NOT NULL
  , FK_Year TITLE 'FK_Year' VARCHAR(8) NOT NULL
  , FOREIGN KEY (FK_Year)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.C_Fin_Last_Tran_Year (Code)
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.C_Fin_Last_Tran_Year (
  Code TITLE 'Code' VARCHAR(8) NOT NULL
  , Name TITLE 'Name' VARCHAR(9) NOT NULL
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.C_Fin_Year (
  Code TITLE 'Code' VARCHAR(8) NOT NULL
  , Name TITLE 'Name' VARCHAR(9) NOT NULL
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.C_Gender (
  Code TITLE 'Code' VARCHAR(14) NOT NULL
  , Name TITLE 'Name' VARCHAR(14) NOT NULL
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.C_Geography_0 (
  Code TITLE 'Code' INTEGER NOT NULL
  , Name TITLE 'Name' VARCHAR(50) NOT NULL
  , FK_SSD TITLE 'FK_SSD' INTEGER NOT NULL
  , FOREIGN KEY (FK_SSD)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.C_Geography_1 (Code)
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.C_Geography_1 (
  Code TITLE 'Code' INTEGER NOT NULL
  , Name TITLE 'Name' VARCHAR(100) NOT NULL
  , FK_SD TITLE 'FK_SD' INTEGER NOT NULL
  , FOREIGN KEY (FK_SD)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.C_Geography_2 (Code)
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.C_Geography_2 (
  Code TITLE 'Code' INTEGER NOT NULL
  , Name TITLE 'Name' VARCHAR(100) NOT NULL
  , FK_State TITLE 'FK_State' INTEGER NOT NULL
  , FOREIGN KEY (FK_State)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.C_State (Code)
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.C_Marital_Status (
  Code TITLE 'Code' VARCHAR(14) NOT NULL
  , Name TITLE 'Name' VARCHAR(14) NOT NULL
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.C_Month (
  Code TITLE 'Code' INTEGER NOT NULL
  , Name TITLE 'Name' VARCHAR(32) NOT NULL
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.C_Occupation (
  Code TITLE 'Code' VARCHAR(2) NOT NULL
  , Name TITLE 'Name' VARCHAR(49) NOT NULL
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.C_Product_Type (
  Code TITLE 'Code' VARCHAR(1) NOT NULL
  , Name TITLE 'Name' VARCHAR(19) NOT NULL
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.C_Quarter (
  Code TITLE 'Code' INTEGER NOT NULL
  , Name TITLE 'Name' VARCHAR(32) NOT NULL
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.C_State (
  Code TITLE 'Code' INTEGER NOT NULL
  , Name TITLE 'Name' VARCHAR(100) NOT NULL
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.C_Week (
  Code TITLE 'Code' INTEGER NOT NULL
  , Name TITLE 'Name' VARCHAR(32) NOT NULL
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.C_WeekDay (
  Code TITLE 'Code' INTEGER NOT NULL
  , Name TITLE 'Name' VARCHAR(32) NOT NULL
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.DATABASE_LABEL (
  LABEL TITLE 'LABEL' VARCHAR(128) NOT NULL
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.FACTS (
  TABLENAME TITLE 'TABLENAME' VARCHAR(128) NOT NULL
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.F_Account (
  PK_Acc_Key TITLE 'PK_Acc_Key' INTEGER NOT NULL
  , Acc_Open_Date TITLE 'Acc_Open_Date' None NOT NULL
  , Acc_Open_Date_Cal TITLE 'Acc_Open_Date_Cal' None NOT NULL
  , Acc_Open_Date_Fin TITLE 'Acc_Open_Date_Fin' None NOT NULL
  , Acc_Open_Date_Quarter TITLE 'Acc_Open_Date_Quarter' None NOT NULL
  , Acc_Open_Date_Month TITLE 'Acc_Open_Date_Month' None NOT NULL
  , Acc_Open_Date_Week TITLE 'Acc_Open_Date_Week' None NOT NULL
  , Acc_Open_Date_DayofMonth TITLE 'Acc_Open_Date_DayofMonth' None NOT NULL
  , Acc_Open_Date_DayofWeek TITLE 'Acc_Open_Date_DayofWeek' None NOT NULL
  , Acc_Profit TITLE 'Acc_Profit' None NOT NULL
  , Avg_Acc_Balance TITLE 'Avg_Acc_Balance' None NOT NULL
  , Last_Transaction_Date TITLE 'Last_Transaction_Date' None NOT NULL
  , Last_Transaction_Date_Cal TITLE 'Last_Transaction_Date_Cal' None NOT NULL
  , Last_Transaction_Date_Fin TITLE 'Last_Transaction_Date_Fin' None NOT NULL
  , Last_Transaction_Date_Quarter TITLE 'Last_Transaction_Date_Quarter' None NOT NULL
  , Last_Transaction_Date_Month TITLE 'Last_Transaction_Date_Month' None NOT NULL
  , Last_Transaction_Date_Week TITLE 'Last_Transaction_Date_Week' None NOT NULL
  , Last_Transaction_Date_DayofMonth TITLE 'Last_Transaction_Date_DayofMonth' None NOT NULL
  , Last_Transaction_Date_DayofWeek TITLE 'Last_Transaction_Date_DayofWeek' None NOT NULL
  , Product_Type TITLE 'Product_Type' None NOT NULL
  , FK_Cust_Key TITLE 'FK_Cust_Key' INTEGER NOT NULL
  , FOREIGN KEY (Acc_Open_Date_Cal)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.C_Cal_Date_0 (Code)
  , FOREIGN KEY (Acc_Open_Date_Fin)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.C_Fin_Date_0 (Code)
  , FOREIGN KEY (Acc_Open_Date_Quarter)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.C_Quarter (Code)
  , FOREIGN KEY (Acc_Open_Date_Month)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.C_Month (Code)
  , FOREIGN KEY (Acc_Open_Date_Week)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.C_Week (Code)
  , FOREIGN KEY (Acc_Open_Date_DayofMonth)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.C_DayOfMonth (Code)
  , FOREIGN KEY (Acc_Open_Date_DayofWeek)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.C_WeekDay (Code)
  , FOREIGN KEY (Last_Transaction_Date_Cal)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.C_Cal_Last_Tran_Date_0 (Code)
  , FOREIGN KEY (Last_Transaction_Date_Fin)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.C_Fin_Last_Tran_Date_0 (Code)
  , FOREIGN KEY (Last_Transaction_Date_Quarter)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.C_Quarter (Code)
  , FOREIGN KEY (Last_Transaction_Date_Month)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.C_Month (Code)
  , FOREIGN KEY (Last_Transaction_Date_Week)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.C_Week (Code)
  , FOREIGN KEY (Last_Transaction_Date_DayofMonth)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.C_DayOfMonth (Code)
  , FOREIGN KEY (Last_Transaction_Date_DayofWeek)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.C_WeekDay (Code)
  , FOREIGN KEY (Product_Type)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.C_Product_Type (Code)
  , FOREIGN KEY (FK_Cust_Key)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.F_Customer (PK_Cust_Key)
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.F_Customer (
  PK_Cust_Key TITLE 'PK_Cust_Key' INTEGER NOT NULL
  , Age TITLE 'Age' INTEGER NOT NULL
  , Age_Group TITLE 'Age_Group' INTEGER NOT NULL
  , Area TITLE 'Area' INTEGER NOT NULL
  , Cust_Mail_Ind TITLE 'Cust_Mail_Ind' VARCHAR(50) NOT NULL
  , Cust_Open_Date TITLE 'Cust_Open_Date' None NOT NULL
  , Cust_Open_Date_Cal TITLE 'Cust_Open_Date_Cal' INTEGER NOT NULL
  , Cust_Open_Date_Fin TITLE 'Cust_Open_Date_Fin' INTEGER NOT NULL
  , Cust_Open_Date_Quarter TITLE 'Cust_Open_Date_Quarter' INTEGER NOT NULL
  , Cust_Open_Date_Month TITLE 'Cust_Open_Date_Month' INTEGER NOT NULL
  , Cust_Open_Date_Week TITLE 'Cust_Open_Date_Week' INTEGER NOT NULL
  , Cust_Open_Date_DayofMonth TITLE 'Cust_Open_Date_DayofMonth' INTEGER NOT NULL
  , Cust_Open_Date_DayofWeek TITLE 'Cust_Open_Date_DayofWeek' INTEGER NOT NULL
  , Cust_Profit TITLE 'Cust_Profit' FLOAT NOT NULL
  , Marital_Status TITLE 'Marital_Status' VARCHAR(50) NOT NULL
  , Occupation TITLE 'Occupation' VARCHAR(50) NOT NULL
  , Gender TITLE 'Gender' VARCHAR(50) NOT NULL
  , Birth_Date TITLE 'Birth_Date' None NOT NULL
  , Company TITLE 'Company' VARCHAR(10) NOT NULL
  , X_Coord TITLE 'X_Coord' VARCHAR(50) NOT NULL
  , Y_Coord TITLE 'Y_Coord' VARCHAR(50) NOT NULL
  , FOREIGN KEY (Age)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.C_Age (Code)
  , FOREIGN KEY (Age_Group)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.C_Age_Group_0 (Code)
  , FOREIGN KEY (Area)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.C_Geography_0 (Code)
  , FOREIGN KEY (Cust_Mail_Ind)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.C_Cust_Mail_Indicator (Code)
  , FOREIGN KEY (Cust_Open_Date_Cal)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.C_Cal_Date_0 (Code)
  , FOREIGN KEY (Cust_Open_Date_Fin)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.C_Fin_Date_0 (Code)
  , FOREIGN KEY (Cust_Open_Date_Quarter)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.C_Quarter (Code)
  , FOREIGN KEY (Cust_Open_Date_Month)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.C_Month (Code)
  , FOREIGN KEY (Cust_Open_Date_Week)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.C_Week (Code)
  , FOREIGN KEY (Cust_Open_Date_DayofMonth)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.C_DayOfMonth (Code)
  , FOREIGN KEY (Cust_Open_Date_DayofWeek)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.C_WeekDay (Code)
  , FOREIGN KEY (Marital_Status)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.C_Marital_Status (Code)
  , FOREIGN KEY (Occupation)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.C_Occupation (Code)
  , FOREIGN KEY (Gender)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.C_Gender (Code)
  , FOREIGN KEY (Company)
    REFERENCES WITH NO CHECK OPTION PRD_ADS_HWD_NHWDSCUBE_DB.Company (code)
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.GROUP (
  TYPE TITLE 'TYPE' VARCHAR(128) NOT NULL
  , DISPLAYNAME TITLE 'DISPLAYNAME' VARCHAR(128) NOT NULL
  , TABLENAME TITLE 'TABLENAME' VARCHAR(128) NOT NULL
  , COLUMNNAME TITLE 'COLUMNNAME' VARCHAR(128) NOT NULL
  , PARENTNAME TITLE 'PARENTNAME' VARCHAR(128) NOT NULL
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.MEASURES (
  COLUMNNAME TITLE 'COLUMNNAME' VARCHAR(128) NOT NULL
  , TABLENAME TITLE 'TABLENAME' VARCHAR(128) NOT NULL
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.MULTIRESPONSES (
  TABLENAME TITLE 'TABLENAME' VARCHAR(128) NOT NULL
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.TABLE_LABEL (
  TABLENAME TITLE 'TABLENAME' VARCHAR(128) NOT NULL
  , LABEL TITLE 'LABEL' VARCHAR(128) NOT NULL
)
;
CREATE TABLE PRD_ADS_HWD_NHWDSCUBE_DB.__SUPER_CHANNEL__ (
  reg_key TITLE 'reg_key' VARCHAR(128) NOT NULL
  , reg_value TITLE 'reg_value' VARCHAR(128) NOT NULL
)
;