select
  'DROP TABLE '||databasename||'.'||tablename||';' as script
from
  dbc.tablesv
where
  databasename='PRD_ADS_HWD_RETAILBANKING_DB'
order by 
  tablename
;

/*Order is important*/
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.F_Account;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.F_Customer;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.Company;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Age_Group_0;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Age;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Age_Ten_Group_1;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Age_Five_Group_1;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Cal_Date_0;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Cal_Date_1;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Cal_Date_2;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Cal_Last_Tran_Date_0;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Cal_Last_Tran_Date_1;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Cal_Last_Tran_Date_2;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Cal_Last_Tran_Year;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Cal_Year;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Cust_Mail_Indicator;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_DayOfMonth;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Fin_Date_0;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Fin_Date_1;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Fin_Date_2;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Fin_Last_Tran_Date_0;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Fin_Last_Tran_Date_1;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Fin_Last_Tran_Date_2;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Fin_Last_Tran_Year;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Fin_Year;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Gender;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Geography_0;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Geography_1;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Geography_2;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Marital_Status;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Month;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Occupation;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Product_Type;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Quarter;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_State;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Week;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_WeekDay;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.R_BINS;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.R_CLASSIFICATIONS;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.R_CLEANSING_RULES;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.R_COLUMN_LABEL;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.R_COUNT_DEFAULT;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.R_DATABASE_LABEL;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.R_FACTS;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.R_GROUP;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.R_MEASURES;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.R_TABLE_LABEL;
DROP TABLE PRD_ADS_HWD_RETAILBANKING_DB.__SUPER_CHANNEL__;