/*DROP constraints to tables after load
*/

ALTER TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Age_Group_0 
DROP CONSTRAINT FK_5Group
;
ALTER TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Age_Group_0 
DROP CONSTRAINT FK_10Group
;
ALTER TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Cal_Date_0 
DROP CONSTRAINT FK_Month
;
ALTER TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Cal_Date_1 
DROP CONSTRAINT FK_Quarter
;
ALTER TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Cal_Date_2 
DROP CONSTRAINT FK_Year
;
ALTER TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Cal_Last_Tran_Date_0 
DROP CONSTRAINT FK_Month
;
ALTER TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Cal_Last_Tran_Date_1 
DROP CONSTRAINT FK_Quarter
;
ALTER TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Cal_Last_Tran_Date_2 
DROP CONSTRAINT FK_Year
;
ALTER TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Fin_Date_0 
DROP CONSTRAINT FK_Month
;
ALTER TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Fin_Date_1 
DROP CONSTRAINT FK_Quarter
;
ALTER TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Fin_Date_2 
DROP CONSTRAINT FK_Year
;
ALTER TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Fin_Last_Tran_Date_0 
DROP CONSTRAINT FK_Month
;
ALTER TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Fin_Last_Tran_Date_1 
DROP CONSTRAINT FK_Quarter
;
ALTER TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Fin_Last_Tran_Date_2 
DROP CONSTRAINT FK_Year
;
ALTER TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Geography_0 
DROP CONSTRAINT FK_SSD
;
ALTER TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Geography_1 
DROP CONSTRAINT FK_SD
;
ALTER TABLE PRD_ADS_HWD_RETAILBANKING_DB.C_Geography_2  
DROP CONSTRAINT FK_State 
;
ALTER TABLE PRD_ADS_HWD_RETAILBANKING_DB.F_Account 
DROP CONSTRAINT FK_Cust_Key
;
